#c/5=(f-32)/9=(k-273.15)/5
#Celsius   Kelvin   Fahrenheit

TYPE=input("SELECT THE TEMPERATURE SCALE YOU ARE ENTERING:").strip().upper()
if TYPE=="CELSIUS":
    CELSIUS=(input("PLS GIVE THE TEMPERATURE READING IN CELSIUS:"))
    try:
        CELSIUS=float(CELSIUS)
        KELVIN=CELSIUS+273.15
        FAHRENHEIT=(9/5)*CELSIUS+32
        print(f"THE TEMPERATURE READINGS IN KELVIN IS {KELVIN} AND IN FAHRENHEIT IS {FAHRENHEIT}")

    except ValueError:
        print("PLS ENTER A NUMBER NOT WORDS")


elif TYPE=="KELVIN":
    KELVIN=input("PLS GIVE THE TEMPERATURE READING IN KELVIN:")
    try:
        KELVIN=float(KELVIN)
        CELSIUS=KELVIN-273.15
        FAHRENHEIT=(9/5)*(KELVIN-273.15)+32
        print(f"THE TEMPERATURE READINGS IN CELSIUS IS {CELSIUS} AND IN FAHRENHEIT IS {FAHRENHEIT}")

    except ValueError:
        print("PLS ENTER A NUMBER NOT WORDS")


elif TYPE=="FAHRENHEIT":
    FAHRENHEIT=(input("PLS GIVE THE TEMPERATURE READING IN FAHRENHEIT:"))
    try:
        FAHRENHEIT=float(FAHRENHEIT)
        CELSIUS=(5/9)*(FAHRENHEIT-32)
        KELVIN=(5/9)*(FAHRENHEIT-32)+273.15
        print(f"THE TEMEPARATURE READINGS IN CELSIUS IS {CELSIUS} AND IN KELVIN IS {KELVIN}")

    except ValueError:
        print("PLS ENTER A NUMBER NOT WORDS")


else:
    print("YOU ENTERD INVALID DETAILS PLS CHECK AND ENTER PEOPERLY FOR THE CONVERSION OF TEMPERATURE")

